website:
  urls: https://www.olx.com.br/imoveis/estado-sc/florianopolis-e-regiao/grande-florianopolis,https://www.olx.com.br/imoveis/aluguel/estado-sc/florianopolis-e-regiao/continente,https://ibagy.com.br/aluguel/comercial/florianopolis/,https://ibagy.com.br/aluguel/apartamento/florianopolis/,https://ibagy.com.br/aluguel/casa/florianopolis/
